import React from 'react';
import ReactDOM from 'react-dom';
import MuiThemeProvider from 'material-ui/styles/MuiThemeProvider';
import MyAwesomeReactComponent from './MyAwesomeReactComponent';
import MyMenu from './MyMenu';
alert("indexjs");
const App = () =>(<MuiThemeProvider><MyAwesomeReactComponent /></MuiThemeProvider>);
const Menus = () =>(<MuiThemeProvider><MyMenu /></MuiThemeProvider>);
ReactDOM.render(<App />,document.getElementById('App'));
ReactDOM.render(<Menus />,document.getElementById('Menus'));
